function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Rider_Controls_Control"};
	this.sidHashMap["Rider_Controls_Control"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Rider_Controls_Control:59"};
	this.sidHashMap["Rider_Controls_Control:59"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Throttle %"] = {sid: "Rider_Controls_Control:31"};
	this.sidHashMap["Rider_Controls_Control:31"] = {rtwname: "<Root>/Throttle %"};
	this.rtwnameHashMap["<Root>/RPM"] = {sid: "Rider_Controls_Control:55"};
	this.sidHashMap["Rider_Controls_Control:55"] = {rtwname: "<Root>/RPM"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "Rider_Controls_Control:60"};
	this.sidHashMap["Rider_Controls_Control:60"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/RPM to Max Motor Current"] = {sid: "Rider_Controls_Control:56"};
	this.sidHashMap["Rider_Controls_Control:56"] = {rtwname: "<Root>/RPM to Max Motor Current"};
	this.rtwnameHashMap["<Root>/Saturation"] = {sid: "Rider_Controls_Control:61"};
	this.sidHashMap["Rider_Controls_Control:61"] = {rtwname: "<Root>/Saturation"};
	this.rtwnameHashMap["<Root>/Saturation Dynamic"] = {sid: "Rider_Controls_Control:59"};
	this.sidHashMap["Rider_Controls_Control:59"] = {rtwname: "<Root>/Saturation Dynamic"};
	this.rtwnameHashMap["<Root>/To % Current"] = {sid: "Rider_Controls_Control:57"};
	this.sidHashMap["Rider_Controls_Control:57"] = {rtwname: "<Root>/To % Current"};
	this.rtwnameHashMap["<Root>/Motor Current %"] = {sid: "Rider_Controls_Control:32"};
	this.sidHashMap["Rider_Controls_Control:32"] = {rtwname: "<Root>/Motor Current %"};
	this.rtwnameHashMap["<Root>/Lookup"] = {sid: "Rider_Controls_Control:62"};
	this.sidHashMap["Rider_Controls_Control:62"] = {rtwname: "<Root>/Lookup"};
	this.rtwnameHashMap["<S1>/up"] = {sid: "Rider_Controls_Control:59:1"};
	this.sidHashMap["Rider_Controls_Control:59:1"] = {rtwname: "<S1>/up"};
	this.rtwnameHashMap["<S1>/u"] = {sid: "Rider_Controls_Control:59:2"};
	this.sidHashMap["Rider_Controls_Control:59:2"] = {rtwname: "<S1>/u"};
	this.rtwnameHashMap["<S1>/lo"] = {sid: "Rider_Controls_Control:59:3"};
	this.sidHashMap["Rider_Controls_Control:59:3"] = {rtwname: "<S1>/lo"};
	this.rtwnameHashMap["<S1>/Data Type Duplicate"] = {sid: "Rider_Controls_Control:59:4"};
	this.sidHashMap["Rider_Controls_Control:59:4"] = {rtwname: "<S1>/Data Type Duplicate"};
	this.rtwnameHashMap["<S1>/Data Type Propagation"] = {sid: "Rider_Controls_Control:59:5"};
	this.sidHashMap["Rider_Controls_Control:59:5"] = {rtwname: "<S1>/Data Type Propagation"};
	this.rtwnameHashMap["<S1>/LowerRelop1"] = {sid: "Rider_Controls_Control:59:6"};
	this.sidHashMap["Rider_Controls_Control:59:6"] = {rtwname: "<S1>/LowerRelop1"};
	this.rtwnameHashMap["<S1>/Switch"] = {sid: "Rider_Controls_Control:59:7"};
	this.sidHashMap["Rider_Controls_Control:59:7"] = {rtwname: "<S1>/Switch"};
	this.rtwnameHashMap["<S1>/Switch2"] = {sid: "Rider_Controls_Control:59:8"};
	this.sidHashMap["Rider_Controls_Control:59:8"] = {rtwname: "<S1>/Switch2"};
	this.rtwnameHashMap["<S1>/UpperRelop"] = {sid: "Rider_Controls_Control:59:9"};
	this.sidHashMap["Rider_Controls_Control:59:9"] = {rtwname: "<S1>/UpperRelop"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "Rider_Controls_Control:59:10"};
	this.sidHashMap["Rider_Controls_Control:59:10"] = {rtwname: "<S1>/y"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
