ASFLAGS_ADDITIONAL = --float_support=fpu32
TARGET_LOAD_CMD = "$(TARGET_SCRIPTING_ROOT)/bin/dss.bat"
TARGET_LOAD_CMD_ARGS = C:\PROGRA~1\MATLAB\R2014b/toolbox/idelink/EXTENS~1/ticcs/ccsdemos/RUNPRO~1.JS C:\MATLAB\SUPPOR~1\R2014b\TEXASI~1\toolbox\target\SUPPOR~1\tic2000\@SLCUS~1\../CCS_CO~1/F28069~1.CCX
TARGET_PKG_INSTALLDIR = C:/MATLAB/SUPPOR~1/R2014b/TEXASI~1/toolbox/target/SUPPOR~1/tic2000/@SLCUS~1/..
STACK_SIZE = 64
