#define PIEMASK0                       64
#define PIEMASK1                       0
#define PIEMASK2                       0
#define PIEMASK3                       0
#define PIEMASK4                       0
#define PIEMASK5                       0
#define PIEMASK6                       0
#define PIEMASK7                       0
#define PIEMASK8                       0
#define PIEMASK9                       0
#define PIEMASK10                      0
#define PIEMASK11                      0
#define IFRMASK                        1
