ASFLAGS_ADDITIONAL = 
CCSV5INSTALLDIR = C:/ti_2/ccsv5/tools/compiler/C2000_~1.0
CONTROLSUITEINSTALLDIR = C:/ti/CONTRO~1
CCSV5SCRIPTINGDIR = C:/ti_2/ccsv5/ccs_base/SCRIPT~1
TARGET_LOAD_CMD = "$(TARGET_SCRIPTING_ROOT)/bin/dss.bat"
TARGET_LOAD_CMD_ARGS = C:\PROGRA~1\MATLAB\R2014b/toolbox/idelink/EXTENS~1/ticcs/ccsdemos/RUNPRO~1.JS C:\MATLAB\SUPPOR~1\R2014b\TEXASI~1\toolbox\target\SUPPOR~1\tic2000\@SLCUS~1\../CCS_CO~1/F28035~1.CCX
TARGET_PKG_INSTALLDIR = C:/MATLAB/SUPPOR~1/R2014b/TEXASI~1/toolbox/target/SUPPOR~1/tic2000/@SLCUS~1/..
STACK_SIZE = 64
